server {
    listen 8080;
    root ./;
    
    location /cgi-bin {
        root ./;
        allowed_methods GET POST;
        cgi_path /usr/bin/python3;
        cgi_ext .py;
        cgi_processing on;
    }
}
