server {
  listen  1234;
  root ./;

  location /cgi-bin {
    root ./;
    cgi_processing on;
    cgi_path /usr/bin/python3;
    cgi_ext .py;
    allowed_methods GET POST DELETE;
  }

  location /post {
    index large.jpg;
    cgi_path /usr/bin/python3;
    cgi_ext .py .jpg;
    cgi_processing on;
    allowed_methods POST;
  }

  location /get {
    index small.jpg;
    cgi_path /usr/bin/python3;
    cgi_ext .py .jpg;
    cgi_processing on;
    allowed_methods GET;
  }

  location /both {
    index aaaaaa.gif;
    cgi_path /usr/bin/python3;
    cgi_ext .py .gif;
    cgi_processing on;
    allowed_methods POST GET;
  }

  location /all {
    index aaaaaa.gif;
    cgi_path /usr/bin/python3;
    cgi_ext .py .gif;
    cgi_processing on;
    allowed_methods POST GET DELETE;
  }

  location /delete {
    index aaaaaa.gif;
    cgi_path /usr/bin/python3;
    cgi_ext .py .gif;
    cgi_processing on;
    allowed_methods DELETE;
  }

}
