server {
    listen 8080;
    host 127.0.0.1;
    server_name localhost;
    root ./;
    index index.html;
    client_max_body_size 100;
    
    location / {
        allowed_methods GET HEAD;
        autoindex on;
    }

    location /directory {
        root ./YoupyBanane;
        allowed_methods GET HEAD POST;
        autoindex on;
    }

    location ~ \.bla$ {
        root ./YoupyBanane;
        allowed_methods GET HEAD POST;
        cgi_path ./ubuntu_cgi_tester;
    }

    location /cgi-bin {
        root ./;
        allowed_methods GET HEAD POST;
        index test.py;
        cgi_path /usr/bin/python3;
        cgi_ext .py;
    }

    location /uploads {
        root ./uploads;
        allowed_methods GET HEAD POST PUT DELETE;
        autoindex on;
    }

    location /put_test {
        root ./uploads;
        allowed_methods GET HEAD POST PUT DELETE;
        autoindex on;
    }

    location /post_body {
        allowed_methods POST;
        client_max_body_size 100;
    }
}
